<?php declare(strict_types=1);
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/.
 */

namespace FredBradley\CranleighEPQShowcase;

class Settings
{
    private $epq_showcase_settings_options;

    private $post_type;

    public function __construct(CustomPostType $post_type)
    {
        $this->post_type = $post_type;

        add_action('admin_menu', [$this, 'epq_showcase_settings_add_plugin_page']);
        add_action('admin_init', [$this, 'epq_showcase_settings_page_init']);
    }

    public function epq_showcase_settings_add_plugin_page(): void
    {
        add_submenu_page(
            'edit.php?post_type='.$this->post_type->post_type_key,
            'EPQ Showcase Settings', // page_title
            'Settings', // menu_title
            'manage_options', // capability
            'epq-showcase-settings', // menu_slug
            [$this, 'epq_showcase_settings_create_admin_page'] // function
        );
    }

    public function epq_showcase_settings_create_admin_page(): void
    {
        $this->epq_showcase_settings_options = get_option('epq_showcase_settings_option_name'); ?>

        <div class="wrap">
            <h2>EPQ Showcase Settings</h2>
            <p>Settings specifically for the EPQ Showcase Plugin</p>
            <?php settings_errors(); ?>

            <form method="post" action="options.php">
                <?php
                    settings_fields('epq_showcase_settings_option_group');
        do_settings_sections('epq-showcase-settings-admin');
        submit_button(); ?>
            </form>
        </div>
    <?php
    }

    public function epq_showcase_settings_page_init(): void
    {
        register_setting(
            'epq_showcase_settings_option_group', // option_group
            'epq_showcase_settings_option_name', // option_name
            [$this, 'epq_showcase_settings_sanitize'] // sanitize_callback
        );

        add_settings_section(
            'epq_showcase_settings_setting_section', // id
            'Settings', // title
            [$this, 'epq_showcase_settings_section_info'], // callback
            'epq-showcase-settings-admin' // page
        );

        add_settings_field(
            'blurb_from_jlt_0', // id
            'Blurb from JLT', // title
            [$this, 'blurb_from_jlt_0_callback'], // callback
            'epq-showcase-settings-admin', // page
            'epq_showcase_settings_setting_section' // section
        );
    }

    public function epq_showcase_settings_sanitize($input)
    {
        $sanitary_values = [];
        if (isset($input['blurb_from_jlt_0'])) {
            $sanitary_values['blurb_from_jlt_0'] = esc_textarea($input['blurb_from_jlt_0']);
        }

        return $sanitary_values;
    }

    public function epq_showcase_settings_section_info(): void
    {
    }

    public function blurb_from_jlt_0_callback(): void
    {
        if (isset($this->epq_showcase_settings_options['blurb_from_jlt_0'])) {
            $content = esc_attr($this->epq_showcase_settings_options['blurb_from_jlt_0']);
        } else {
            $content = '';
        }

        echo wp_editor(
            $content,
            'jltblurb',
            [
                'textarea_name' => 'epq_showcase_settings_option_name[blurb_from_jlt_0]',
            ]
        );
    }
}
